language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t backend-feed ./udagram-api-feed
  - docker build -t backend-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
    #tagging
  - docker tag udagram-reverseproxy petemuema/udagram-reverseproxy:latest
  - docker tag backend-feed petemuema/udagram-api-feed:latest
  - docker tag backend-user petemuema/udagram-api-user:latest
  - docker tag udagram-frontend petemuema/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push petemuema/udagram-reverseproxy
  - docker push petemuema/backend-feed
  - docker push petemuema/backend-user
  - docker push petemuema/udagram-frontend